https-portal:
  image: steveltn/https-portal
  # You can build from source code rather than use the prebuilt image from Docker Hub.
  # build: ../..
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  # Restart https-portal on failure or after Docker host restart.
  restart: always
  environment:
    # Forward wordpress.example.com to the WordPress container.
    # You can set up multiple domains at once.
    DOMAINS: 'wordpress.example.com -> http://wordpress'

    # Using staging server by default, for there is a rate limit on production.
    # Uncomment to use Let's Encrypt production server.
    # PRODUCTION: 'true'

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: '<a secure password>'
